name: "Dockerfile Lint Action"
description: "Action that runs replicatedhq/dockerfilelint linting tool"
author: "Tim Preece"
inputs:
  dockerfile:
    required: false
    description: "The path to the Dockerfile to lint"
    default: "Dockerfile"
runs:
  using: "docker"
  image: "theyorkshiredev/dockerfile-linter:1.1.0"
  args:
    - ${{ inputs.dockerfile }}
branding:
  icon: "aperture"
  color: "red"
